//! Native code generation for Pika programs with Cranelift.
//!
//! [`compile`] translates every MIR body into Cranelift IR and compiles it into executable
//! memory (a JIT). The translation only uses Cranelift's generic `Module` interface, so
//! producing object files for standalone executables only needs a different module.
//!
//! The generated code follows the reference semantics of `pika_mir::value` exactly; the
//! differential tests run every program both compiled and interpreted.
//!
//! # Representation of values
//!
//! Scalars (integers, floats, `bool`, `char`, `Duration`) are machine values, and so is a
//! box: a pointer to its value on the heap. A `String` is a three-word structure in memory
//! (see `pika_runtime::string::PikaString`), a struct is its fields in memory, laid out as by
//! a C compiler, and an enum or option is a tag followed by the fields of its variant. Locals
//! holding scalars are SSA variables unless their address is taken; other locals live in
//! stack slots. Borrowed parameters are pointers. A function returning a value in memory
//! receives a pointer to the destination as a hidden first parameter.

mod collections;
mod functions;
mod glue;
mod repr;
mod translate;

use std::collections::HashMap;

use cranelift_codegen::ir::{
    AbiParam, InstBuilder, MemFlagsData, Signature, StackSlotData, StackSlotKind, TrapCode, types,
};
use cranelift_codegen::settings::{self, Configurable};
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_jit::{JITBuilder, JITModule};
use cranelift_module::{DataDescription, DataId, FuncId, Linkage, Module};
use la_arena::ArenaMap;
use pika_diagnostics::SourceMap;
use pika_hir::GlobalId;
use pika_mir::{InstanceId, Program, Value};
use pika_types::Ty;

use crate::glue::{Emitter, GlueKind};
use crate::repr::{Layouts, Repr};

/// A failure inside the code generator. It always indicates a compiler bug.
#[derive(Debug)]
pub struct CodegenError(pub String);

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

fn error(context: &str, cause: impl std::fmt::Display) -> CodegenError {
    CodegenError(format!("{context}: {cause}"))
}

/// A compiled program, ready to run.
pub struct Compiled {
    module: JITModule,
    entry: Option<FuncId>,
    finish: FuncId,
}

impl Compiled {
    /// Runs the program's entry point in the current thread, then destroys its globals.
    ///
    /// Output is buffered; call [`pika_runtime::abi::finish`] afterwards to flush it. A panic
    /// in the program exits the process. The caller must have set the stack limit for this
    /// thread with [`pika_runtime::abi::set_stack_limit`].
    pub fn run(&self) {
        let Some(entry) = self.entry else {
            return;
        };
        for function in [entry, self.finish] {
            let code = self.module.get_finalized_function(function);
            #[allow(unsafe_code, reason = "calling code generated by Cranelift")]
            // SAFETY: `function` is a finalized function compiled from the program's `main`
            // or from the generated finalizer; both take no parameters and return nothing,
            // using the target's default calling convention (the C convention). The module,
            // which owns the code, outlives the call.
            unsafe {
                let function: extern "C" fn() =
                    std::mem::transmute::<*const u8, extern "C" fn()>(code);
                function();
            }
        }
    }
}

/// Compiles a program to native code in memory.
///
/// # Errors
///
/// Fails only on internal errors of the code generator.
/// Panic locations refer to the files of `sources` by index: the runtime must be given their
/// names with `pika_runtime::set_program_files`.
pub fn compile(program: &Program, sources: &SourceMap) -> Result<Compiled, CodegenError> {
    let mut flags = settings::builder();
    for (name, value) in [
        ("use_colocated_libcalls", "false"),
        ("is_pic", "false"),
        ("opt_level", "speed"),
    ] {
        flags.set(name, value).map_err(|e| error(name, e))?;
    }
    let isa = cranelift_native::builder()
        .map_err(|e| error("unsupported host", e))?
        .finish(settings::Flags::new(flags))
        .map_err(|e| error("creating the target", e))?;
    let mut builder = JITBuilder::with_isa(isa, cranelift_module::default_libcall_names());
    for (name, address) in pika_runtime::abi::symbols() {
        builder.symbol(name, address);
    }
    let mut module = JITModule::new(builder);

    let runtime = Runtime::declare(&mut module)?;
    let stack_limit = module
        .declare_data("pika_stack_limit", Linkage::Import, true, false)
        .map_err(|e| error("declaring the stack limit", e))?;
    let mut ctx = ModuleCtx {
        functions: ArenaMap::default(),
        drop_fns: program.drop_fns.clone(),
        display_fns: program.display_fns.clone(),
        globals: ArenaMap::default(),
        strings: HashMap::new(),
        runtime,
        stack_limit,
        layouts: Layouts::new(&program.types),
        glue: HashMap::new(),
        pending_glue: Vec::new(),
        env_drops: HashMap::new(),
        pending_env_drops: Vec::new(),
    };
    for (id, body) in program.functions.iter() {
        let signature = ctx.layouts.signature(&module, body);
        let name = format!("pika_fn_{}_{}", body.name, id.into_raw().into_u32());
        let func = module
            .declare_function(&name, Linkage::Local, &signature)
            .map_err(|e| error("declaring a function", e))?;
        ctx.functions.insert(id, (func, signature));
    }
    for (id, global) in program.globals.iter() {
        let data = define_global(
            &mut module,
            &mut ctx,
            &global.name,
            global.ty,
            &global.value,
        )?;
        ctx.globals.insert(id, data);
    }

    let mut context = module.make_context();
    let mut builder_context = FunctionBuilderContext::new();
    for (id, body) in program.functions.iter() {
        let (func, signature) = ctx.functions[id].clone();
        context.func.signature = signature;
        translate::translate_body(
            &mut module,
            &mut ctx,
            program,
            body,
            &mut context.func,
            &mut builder_context,
            sources,
        )?;
        module
            .define_function(func, &mut context)
            .map_err(|e| CodegenError(format!("compiling `{}`: {e:?}", body.name)))?;
        module.clear_context(&mut context);
    }
    let finish = define_finish(
        &mut module,
        &mut ctx,
        program,
        &mut context,
        &mut builder_context,
    )?;
    let entry = define_entry(
        &mut module,
        &mut ctx,
        program,
        &mut context,
        &mut builder_context,
    )?;
    glue::define_pending(&mut module, &mut ctx, &mut context, &mut builder_context)?;
    module
        .finalize_definitions()
        .map_err(|e| error("finalizing", e))?;
    Ok(Compiled {
        module,
        entry,
        finish,
    })
}

/// Defines the data of a global with its initial value. Strings in it initially refer to
/// static text (capacity 0), so they need no allocation.
fn define_global(
    module: &mut JITModule,
    ctx: &mut ModuleCtx,
    name: &str,
    ty: Ty,
    value: &Value,
) -> Result<DataId, CodegenError> {
    let data = module
        .declare_data(&format!("pika_global_{name}"), Linkage::Local, true, false)
        .map_err(|e| error("declaring a global", e))?;
    let (size, align) = match ctx.layouts.repr(ty) {
        Repr::Scalar(scalar) => (scalar.bytes(), scalar.bytes()),
        Repr::Memory { size, align } => (size, u32::from(align)),
        Repr::None => (0, 1),
    };
    let mut bytes = vec![0u8; size as usize];
    let mut texts = Vec::new();
    ctx.layouts.encode(value, &mut bytes, 0, &mut texts);
    let mut description = DataDescription::new();
    description.define(bytes.into_boxed_slice());
    description.set_align(u64::from(align));
    for (offset, text) in texts {
        let text_data = ctx.string_data(module, &text)?;
        let text_value = module.declare_data_in_data(text_data, &mut description);
        let offset = u32::try_from(offset).expect("globals are small");
        description.write_data_addr(offset, text_value, 0);
    }
    module
        .define_data(data, &description)
        .map_err(|e| error("defining a global", e))?;
    Ok(data)
}

/// The function that runs the program: `main`, or a function that runs a `main` that
/// raises and reports its error.
fn define_entry(
    module: &mut JITModule,
    ctx: &mut ModuleCtx,
    program: &Program,
    context: &mut cranelift_codegen::Context,
    builder_context: &mut FunctionBuilderContext,
) -> Result<Option<FuncId>, CodegenError> {
    let Some(id) = program.entry else {
        return Ok(None);
    };
    let Some(&(main, _)) = ctx.functions.get(id) else {
        return Ok(None);
    };
    if !program.functions[id].raises {
        return Ok(Some(main));
    }
    define_start(module, ctx, program, main, context, builder_context).map(Some)
}

/// Defines the function that runs a `main` that raises: it gives `main` an `Error?` and
/// reports the error it holds afterwards, if any.
fn define_start(
    module: &mut JITModule,
    ctx: &mut ModuleCtx,
    program: &Program,
    main: FuncId,
    context: &mut cranelift_codegen::Context,
    builder_context: &mut FunctionBuilderContext,
) -> Result<FuncId, CodegenError> {
    let error_ty = program.types.error_ty();
    let option_ty = Ty::option(error_ty);
    let layouts = &ctx.layouts;
    let missing = || CodegenError("no layout for errors".to_owned());
    let (option_size, option_align) = layouts.size_align(option_ty);
    let payload = layouts
        .variant_field_offset(option_ty, 1, 0)
        .ok_or_else(missing)?;
    let fields: Vec<u32> = layouts
        .layout(error_ty)
        .ok_or_else(missing)?
        .fields()
        .iter()
        .map(|&(_, _, offset)| offset)
        .collect();
    let source_ty = Ty::option(Ty::boxed(error_ty));
    let source_box = layouts
        .variant_field_offset(source_ty, 1, 0)
        .ok_or_else(missing)?;
    // As `pika_runtime::abi::ErrorLayout`.
    let error_layout = [
        fields[0], fields[1], source_box, fields[2], fields[3], fields[4],
    ];

    let signature = module.make_signature();
    let func = module
        .declare_function("pika_start", Linkage::Local, &signature)
        .map_err(|e| error("declaring the start function", e))?;
    context.func.signature = signature;
    {
        let mut builder = FunctionBuilder::new(&mut context.func, builder_context);
        let pointer = module.target_config().pointer_type();
        let entry = builder.create_block();
        builder.switch_to_block(entry);
        let slot = builder.create_sized_stack_slot(StackSlotData::new(
            StackSlotKind::ExplicitSlot,
            option_size,
            option_align
                .trailing_zeros()
                .try_into()
                .expect("small alignment"),
        ));
        let address = builder.ins().stack_addr(pointer, slot, 0);
        let none = builder.ins().iconst(types::I32, 0);
        builder
            .ins()
            .store(MemFlagsData::trusted(), none, address, 0);
        let main_ref = module.declare_func_in_func(main, builder.func);
        builder.ins().call(main_ref, &[address]);
        let tag = builder
            .ins()
            .load(types::I32, MemFlagsData::trusted(), address, 0);
        let (raised, done) = (builder.create_block(), builder.create_block());
        builder.ins().brif(tag, raised, &[], done, &[]);

        builder.switch_to_block(raised);
        let layout_slot = builder.create_sized_stack_slot(StackSlotData::new(
            StackSlotKind::ExplicitSlot,
            4 * 6,
            2,
        ));
        let layout_address = builder.ins().stack_addr(pointer, layout_slot, 0);
        for (index, offset) in error_layout.iter().enumerate() {
            let value = builder.ins().iconst(types::I32, i64::from(*offset));
            let at = i32::try_from(index * 4).expect("small offsets");
            builder
                .ins()
                .store(MemFlagsData::trusted(), value, layout_address, at);
        }
        let payload = builder.ins().iconst(pointer, i64::from(payload));
        let error_address = builder.ins().iadd(address, payload);
        let uncaught = module.declare_func_in_func(ctx.runtime.uncaught, builder.func);
        builder
            .ins()
            .call(uncaught, &[error_address, layout_address]);
        builder.ins().trap(TrapCode::unwrap_user(3));

        builder.switch_to_block(done);
        builder.ins().return_(&[]);
        builder.seal_all_blocks();
        builder.finalize(module.target_config());
    }
    module
        .define_function(func, context)
        .map_err(|e| CodegenError(format!("compiling the start function: {e:?}")))?;
    module.clear_context(context);
    Ok(func)
}

/// Defines the function run after `main`: it destroys globals that own resources.
fn define_finish(
    module: &mut JITModule,
    ctx: &mut ModuleCtx,
    program: &Program,
    context: &mut cranelift_codegen::Context,
    builder_context: &mut FunctionBuilderContext,
) -> Result<FuncId, CodegenError> {
    let signature = module.make_signature();
    let func = module
        .declare_function("pika_finish", Linkage::Local, &signature)
        .map_err(|e| error("declaring the finalizer", e))?;
    context.func.signature = signature;
    {
        let mut builder = FunctionBuilder::new(&mut context.func, builder_context);
        let entry = builder.create_block();
        builder.switch_to_block(entry);
        let pointer = module.target_config().pointer_type();
        for (id, global) in program.globals.iter() {
            if ctx.layouts.needs_drop(global.ty) {
                let value = module.declare_data_in_func(ctx.globals[id], builder.func);
                let address = builder.ins().symbol_value(pointer, value);
                let mut emitter = Emitter {
                    builder: &mut builder,
                    module,
                    ctx,
                    pointer,
                };
                emitter.drop_value(address, global.ty)?;
            }
        }
        builder.ins().return_(&[]);
        builder.seal_all_blocks();
        builder.finalize(module.target_config());
    }
    module
        .define_function(func, context)
        .map_err(|e| CodegenError(format!("compiling the finalizer: {e:?}")))?;
    module.clear_context(context);
    Ok(func)
}

/// Module-level declarations shared by all function translations.
pub(crate) struct ModuleCtx {
    pub(crate) functions: ArenaMap<InstanceId, (FuncId, Signature)>,
    /// The `drop` function of each type that has one.
    pub(crate) drop_fns: HashMap<Ty, InstanceId>,
    /// The `fmt` function of each type that has one.
    pub(crate) display_fns: HashMap<Ty, InstanceId>,
    pub(crate) globals: ArenaMap<GlobalId, DataId>,
    /// Read-only data for each distinct text.
    pub(crate) strings: HashMap<String, DataId>,
    pub(crate) runtime: Runtime,
    pub(crate) stack_limit: DataId,
    pub(crate) layouts: Layouts,
    /// The glue functions of structs and enums, by type and operation.
    pub(crate) glue: HashMap<(Ty, GlueKind), FuncId>,
    /// Glue functions declared but not defined yet.
    pub(crate) pending_glue: Vec<(Ty, GlueKind, FuncId)>,
    /// The function that destroys the captures of the function values of each body, if
    /// any needs it.
    pub(crate) env_drops: HashMap<InstanceId, Option<FuncId>>,
    /// Capture destructors declared but not defined yet, with the captures' types.
    pub(crate) pending_env_drops: Vec<(FuncId, Vec<Ty>)>,
}

impl ModuleCtx {
    /// The read-only data holding `text`, defined on first use.
    pub(crate) fn string_data(
        &mut self,
        module: &mut JITModule,
        text: &str,
    ) -> Result<DataId, CodegenError> {
        if let Some(&data) = self.strings.get(text) {
            return Ok(data);
        }
        let name = format!("pika_str_{}", self.strings.len());
        let data = module
            .declare_data(&name, Linkage::Local, false, false)
            .map_err(|e| error("declaring text", e))?;
        let mut description = DataDescription::new();
        // A non-empty buffer, so that even empty text has a valid address.
        let mut bytes = text.as_bytes().to_vec();
        if bytes.is_empty() {
            bytes.push(0);
        }
        description.define(bytes.into_boxed_slice());
        module
            .define_data(data, &description)
            .map_err(|e| error("defining text", e))?;
        self.strings.insert(text.to_owned(), data);
        Ok(data)
    }
}

/// The runtime functions called by generated code.
pub(crate) struct Runtime {
    pub(crate) print_i64: FuncId,
    pub(crate) print_u64: FuncId,
    pub(crate) print_f64: FuncId,
    pub(crate) print_f32: FuncId,
    pub(crate) print_bool: FuncId,
    pub(crate) print_char: FuncId,
    pub(crate) print_duration: FuncId,
    pub(crate) print_str: FuncId,
    pub(crate) print_string: FuncId,
    pub(crate) print_newline: FuncId,
    pub(crate) panic_begin: FuncId,
    pub(crate) panic_end: FuncId,
    pub(crate) panic: FuncId,
    pub(crate) uncaught: FuncId,
    pub(crate) rem_f64: FuncId,
    pub(crate) rem_f32: FuncId,
    pub(crate) string_new: FuncId,
    pub(crate) intrinsic: FuncId,
    pub(crate) alloc: FuncId,
    pub(crate) free: FuncId,
    pub(crate) list_reserve: FuncId,
    pub(crate) list_free: FuncId,
    pub(crate) list_open: FuncId,
    pub(crate) list_close: FuncId,
    pub(crate) map_find: FuncId,
    pub(crate) map_push: FuncId,
    pub(crate) map_remove: FuncId,
    pub(crate) map_clear: FuncId,
    pub(crate) map_free: FuncId,
    pub(crate) hash_bytes: FuncId,
    pub(crate) string_drop: FuncId,
    pub(crate) string_clone: FuncId,
    pub(crate) string_push_bytes: FuncId,
    pub(crate) string_push_string: FuncId,
    pub(crate) string_push_string_quoted: FuncId,
    pub(crate) string_push_char_quoted: FuncId,
    pub(crate) string_push_i64: FuncId,
    pub(crate) string_push_u64: FuncId,
    pub(crate) string_push_f64: FuncId,
    pub(crate) string_push_f32: FuncId,
    pub(crate) string_push_bool: FuncId,
    pub(crate) string_push_char: FuncId,
    pub(crate) string_push_duration: FuncId,
    pub(crate) string_compare: FuncId,
    pub(crate) string_contains: FuncId,
}

impl Runtime {
    fn declare(module: &mut JITModule) -> Result<Self, CodegenError> {
        let pointer = module.target_config().pointer_type();
        let mut declare = |name: &str, params: &[types::Type], ret: Option<types::Type>| {
            let mut signature = module.make_signature();
            signature
                .params
                .extend(params.iter().map(|&t| AbiParam::new(t)));
            signature.returns.extend(ret.map(AbiParam::new));
            module
                .declare_function(name, Linkage::Import, &signature)
                .map_err(|e| error("declaring a runtime function", e))
        };
        let stream = types::I32;
        let p = pointer;
        Ok(Self {
            print_i64: declare("pika_print_i64", &[types::I64, stream], None)?,
            print_u64: declare("pika_print_u64", &[types::I64, stream], None)?,
            print_f64: declare("pika_print_f64", &[types::F64, stream], None)?,
            print_f32: declare("pika_print_f32", &[types::F32, stream], None)?,
            print_bool: declare("pika_print_bool", &[types::I8, stream], None)?,
            print_char: declare("pika_print_char", &[types::I32, stream], None)?,
            print_duration: declare("pika_print_duration", &[types::I64, stream], None)?,
            print_str: declare("pika_print_str", &[p, p, stream], None)?,
            print_string: declare("pika_print_string", &[p, stream], None)?,
            print_newline: declare("pika_print_newline", &[stream], None)?,
            panic_begin: declare("pika_panic_begin", &[types::I32], None)?,
            panic_end: declare(
                "pika_panic_end",
                &[types::I32, types::I32, types::I32],
                None,
            )?,
            panic: declare(
                "pika_panic",
                &[types::I32, types::I32, types::I32, types::I32],
                None,
            )?,
            uncaught: declare("pika_uncaught", &[p, p], None)?,
            rem_f64: declare("pika_rem_f64", &[types::F64, types::F64], Some(types::F64))?,
            rem_f32: declare("pika_rem_f32", &[types::F32, types::F32], Some(types::F32))?,
            string_new: declare("pika_string_new", &[p], None)?,
            intrinsic: declare("pika_intrinsic", &[types::I32, p, p], None)?,
            alloc: declare("pika_alloc", &[p, p], Some(p))?,
            free: declare("pika_free", &[p, p, p], None)?,
            list_reserve: declare("pika_list_reserve", &[p, p, p, p], None)?,
            list_free: declare("pika_list_free", &[p, p, p], None)?,
            list_open: declare("pika_list_open", &[p, p, p, p], Some(p))?,
            list_close: declare("pika_list_close", &[p, p, p], None)?,
            map_find: declare(
                "pika_map_find",
                &[p, types::I64, p, p, p, p],
                Some(types::I64),
            )?,
            map_push: declare("pika_map_push", &[p, types::I64, p, p], Some(p))?,
            map_remove: declare("pika_map_remove", &[p, p, p], None)?,
            map_clear: declare("pika_map_clear", &[p], None)?,
            map_free: declare("pika_map_free", &[p, p, p], None)?,
            hash_bytes: declare("pika_hash_bytes", &[p, p], Some(types::I64))?,
            string_drop: declare("pika_string_drop", &[p], None)?,
            string_clone: declare("pika_string_clone", &[p, p], None)?,
            string_push_bytes: declare("pika_string_push_bytes", &[p, p, p], None)?,
            string_push_string: declare("pika_string_push_string", &[p, p], None)?,
            string_push_string_quoted: declare("pika_string_push_string_quoted", &[p, p], None)?,
            string_push_char_quoted: declare(
                "pika_string_push_char_quoted",
                &[p, types::I32],
                None,
            )?,
            string_push_i64: declare("pika_string_push_i64", &[p, types::I64], None)?,
            string_push_u64: declare("pika_string_push_u64", &[p, types::I64], None)?,
            string_push_f64: declare("pika_string_push_f64", &[p, types::F64], None)?,
            string_push_f32: declare("pika_string_push_f32", &[p, types::F32], None)?,
            string_push_bool: declare("pika_string_push_bool", &[p, types::I8], None)?,
            string_push_char: declare("pika_string_push_char", &[p, types::I32], None)?,
            string_push_duration: declare("pika_string_push_duration", &[p, types::I64], None)?,
            string_compare: declare("pika_string_compare", &[p, p], Some(types::I32))?,
            string_contains: declare("pika_string_contains", &[p, p], Some(types::I8))?,
        })
    }
}
