//! The Pika grammar for [tree-sitter](https://tree-sitter.github.io), used by editors such as
//! Zed for syntax highlighting and structural navigation.
//!
//! The grammar is defined in `grammar.js` and `src/scanner.c`; `src/parser.c` is generated
//! from it by the tree-sitter CLI. Its queries for Zed live in `editors/zed/languages/pika`.
//!
//! ```
//! let mut parser = tree_sitter::Parser::new();
//! parser
//!     .set_language(&tree_sitter_pika::LANGUAGE.into())
//!     .expect("the grammar is compatible with the tree-sitter library");
//! let tree = parser.parse(":put \"Hello, Pika\"", None).expect("parsing succeeds");
//! assert!(!tree.root_node().has_error());
//! ```

use tree_sitter_language::LanguageFn;

#[allow(unsafe_code, reason = "the parser is a C library")]
mod ffi {
    unsafe extern "C" {
        pub(crate) fn tree_sitter_pika() -> *const ();
    }
}

/// The tree-sitter language of Pika.
#[allow(unsafe_code, reason = "the parser is a C library")]
// SAFETY: `tree_sitter_pika` is the language function generated by the tree-sitter CLI and
// compiled by the build script; it takes no arguments and returns a pointer to a static
// `TSLanguage`.
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(ffi::tree_sitter_pika) };

/// The node types of the grammar, as JSON.
pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");
