[package]
name = "pika_codegen"
description = "Native code generation for Pika programs with Cranelift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
pika_ty.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-native.workspace = true
la-arena.workspace = true
pika_diagnostics.workspace = true
pika_hir.workspace = true
pika_mir.workspace = true
pika_runtime.workspace = true
pika_types.workspace = true

[lints]
workspace = true
